import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import { execFileSync } from "child_process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const wasmPlugin = {
	name: "wasm-clang",
	setup(build) {
		build.onLoad({ filter: /\.c$/ }, (args) => {
			const outFile = path.join(
				"/tmp/opencode",
				`${path.basename(args.path)}.wasm`
			);
			execFileSync("clang", [
				"--target=wasm32",
				"-O2",
				"-nostdlib",
				"-Wl,--no-entry",
				"-Wl,--export-memory",
				"-Wl,--strip-all",
				"-o",
				outFile,
				args.path,
			]);
			return {
				contents: fs.readFileSync(outFile),
				loader: "binary",
			};
		});
	},
};

const mupdfPlugin = {
	name: "mupdf-glue",
	setup(build) {
		build.onResolve({ filter: /^mupdf/ }, () => ({
			path: path.resolve("node_modules/mupdf/dist/mupdf-wasm.js"),
		}));
	},
};

const prod = process.argv[2] === "production";

fs.copyFileSync(
	path.resolve("node_modules/mupdf/dist/mupdf-wasm.wasm"),
	path.resolve("mupdf-wasm.wasm")
);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	plugins: [wasmPlugin, mupdfPlugin],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
